### ISSUE TITLE
Please consider switching the rutorrent image

### ISSUE THREAD

**Issue by RXWatcher1** [l3uddz/cloudbox#1]
to this: https://hub.docker.com/r/xeroxmalf/rutorrent-autodl-irssi/

The issue with the linuxserver one is that it doesnt contain a working irssi.

thanks!

**Comment by l3uddz** [comment]
i can do that. i have been looking at other images, but the problem is in order for it to be compatible with the existing codebase, it needs to use a /downloads volume, which it seems this one does. so i will definitely check this one out thanks. do you know if he exposes the themes folder to /config? it was something that had a PR submitted on the linuxserver image, however the maintainer sees no value in being able to set a custom theme so was declined. i'd love to get the material theme added by default if possible.

**Comment by RXWatcher1** [comment]
It doesnt look like he does. I looked at my old config dir file when I ran this about 2 months ago. Themes arent in there. You might have to fork it and add it in there.

My only real issue with this image was that he only exposes 443 and not 80. You might end up with cert issues. I haven't looked at your nginx configs for the reverse proxy.

**Comment by l3uddz** [comment]
yeah I just noticed r.e. no configurable port 80. will have to try it out. atm i havent added support for any certs/reverse proxy nginx. i was interested in adding nginx-proxy and their letsencrypt companion container, but then they dont support just IP's for people who dont want to use a domain which is why i havent really looked further into it. i will experiment later with this image though as im sure people will want autodl-irssi more than being able to customize port 80.

**Comment by l3uddz** [comment]
thanks man, i never considered traefik (heard it mentioned before, just never looked into it). but it certainly looks like it may be the solution here (had a quick look at your github and https://medium.com/@lukastosic/traefik-docker-reverse-proxy-and-much-much-more-a39b24b9d959). a single htpasswd for all containers would be ideal in my eyes. cloudbox isnt trying to be a script that people can use to sell multiple seedbox's to customers on a single system. its mainly designed to automate my setup (single user on a dedicated server), but if others want to use it, then thats fine, although it would require some editing themselves if they wanted to support multiple users.. thanks for the tips. ill definitely look into implementing traefik as it sounds ideal. able to support domains and no domain!

**Comment by RXWatcher1** [comment]
Its all good. I agree, I dont think it should be something for commercial purposes nor multiuser. It was all about supporting friends on the box. Quickbox turned into a mess as people started using it for commercial purposes(something I have opposed since I got involved)...one of the reasons I kinda moved over on my own path and 100% detached from QB.

If I can help in any way, just say so or hit me up on slack. I'm going on holiday for a couple of weeks, I'll see where you're at when I get back and if I can contribute in some way, I'd love to help.

**Comment by l3uddz** [comment]
help is always welcome 👍. atm its been a one man show r.e. the script, with alot of help from a friend with testing. he's currently working on a readme + novice friendly wiki. readmes arent my strong suit as you might have guessed from some of my other projects. im hoping to have it completed before 2 weeks, however there will always be things that crop up. i must have spun up/restored my vm 200 times easily testing each bit as I went along, kernel upgrades do get rather annoying every time. i should really take another snapshot after upgrading the kernel, but its hard to predict how the install will go without also performing something like that, so its easier to just wait for the kernel to upgrade than testing it on before/after kernel snapshots. i'd love todo some more changes r.e. tuning the system for the best possible performance however im thinking ill do more on that when everything is completed, and im at the mercy of people letting me know what can be done to improve system performance. it already does the basics, which you can see in the system role if you feel like taking a look. anyway man, have a good holiday and we'll catch up when your back. thanks again for the advice, traefik is on my todo list.

**Comment by Nottt** [comment]
Why not use your own rutorrent docker?

**Comment by l3uddz** [comment]
Image has autodl irssi now
